server:
  name: "gin-grpc-api"
  addr: "127.0.0.1:80"
zap:
  error_file_name: "../logs_file/error/error.log"
  warn_file_name: "../logs_file/warn/warn.log"
  info_file_name: "../logs_file/info/info.log"
  max_size: 500
  max_age: 28
  max_backups: 3
etcd:
  addrs:
    - "127.0.0.1:2379"
jwt:
  issuer: "zhou"
  secret: "llhn5KCCIaSih1wJc90Xu3aRHVgqsUuB"