server:
  name: "gin-grpc-user"
  addr: "127.0.0.1:8080"
zap:
  error_file_name: "../logs_file/error/error.log"
  warn_file_name: "../logs_file/warn/warn.log"
  info_file_name: "../logs_file/info/info.log"
  max_size: 500
  max_age: 28
  max_backups: 3
redis:
  host: "127.0.0.1"
  port: 16379
  password: ""
  db: 0
grpc:
  addr: "127.0.0.1:8881"
  name: "user"
  version: "1.0.0"
  weight: 2
etcd:
  addrs:
    - "127.0.0.1:2379"
mysql:
  host: "127.0.0.1"
  port: 3309
  user: "root"
  password: "root"
  dbname: "gin-grpc"
  max_idle_conns: 10
  max_open_conns: 50

snow:
  start_time: "2024-04-12"
  machine_id: 1